name: widgetbook_challenge
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  argon_buttons_flutter: ^1.1.0
  cupertino_icons: ^1.0.2
  
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.1
  very_good_analysis: ^2.4.0
  build_runner: ^2.2.1
  
 

flutter:
  uses-material-design: true