// Mocks generated by Mockito 5.3.1 from annotations
// in widgetbook_challenge/test/api/api_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:math' as _i2;

import 'package:mockito/mockito.dart' as _i1;
import 'package:widgetbook_challenge/api/widgetbook_api.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRandom_0 extends _i1.SmartFake implements _i2.Random {
  _FakeRandom_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WidgetbookApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockWidgetbookApi extends _i1.Mock implements _i3.WidgetbookApi {
  MockWidgetbookApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Random get randomNumberGenerator => (super.noSuchMethod(
        Invocation.getter(#randomNumberGenerator),
        returnValue: _FakeRandom_0(
          this,
          Invocation.getter(#randomNumberGenerator),
        ),
      ) as _i2.Random);
  @override
  _i4.Future<String> welcomeToWidgetbook({required String? message}) =>
      (super.noSuchMethod(
        Invocation.method(
          #welcomeToWidgetbook,
          [],
          {#message: message},
        ),
        returnValue: _i4.Future<String>.value(''),
      ) as _i4.Future<String>);
}
